apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysstats
  labels:
    app: sysstats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sysstats
  template:
    metadata:
      labels:
        app: sysstats
    spec:
      containers:
      - name: sysstats
        image: public.ecr.aws/x9v2j5s7/stats-sanif:latest
        ports:
        - containerPort: 80 
      - name: api
        image: public.ecr.aws/x9v2j5s7/sanif/api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sysstats
spec:
  selector:
    app: sysstats
  type: LoadBalancer  
  ports:
    - name: sysstats
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 5000